# Explorer configuration
explorer:
  url: "https://api.ergoplatform.com/api/v1"
  max_retries: 5
  retry_delay: 3.0

# Prometheus configuration
prometheus:
  port: 8008

# Monitoring configuration
monitoring:
  hours_lookback: 24
  check_interval: 15

# Telegram configuration (optional)
telegram:
  # https://api.telegram.org/bot<your_token>/getUpdates
  bot_token: "7463686291:AAHmVccM5BW6ec9q5sO2edqsOEE8Jd7sc7E"  # Optional: remove if not using Telegram

  # Default chat_id for general notifications (optional)
  default_chat_id: "-1002326063811" # 
  default_topic_id: "null"  # null means no specific topic

# Addresses to monitor
addresses:

  - address: "9ehJZvPDgvCNNd2zTQHxnSpcCAtb1kHbEN1VAgeoRD5DPVApYkk"
    nickname: "Mining Wallet"
    telegram_destinations:
      - chat_id: "-1002326063811"
        topic_id: 2
        report_balance: true


  - address: "9f3AaAirSTGYKWqDcw8hEa4Pk4hYiS96VC3Kpcr7CKTuqTiwjCy"
    nickname: "Linux"
    telegram_destinations:
      - chat_id: "-1002326063811"
        topic_id: 4
        report_balance: true
        
  - address: "9hxEvxV6BqPJmWDesy8P1kFoXeQ3wF9ZGxvjak6TAiezr5tu4Sc"
    nickname: "Grid Trading Bot"
    telegram_destinations:
      - chat_id: "-1002326063811"
        topic_id: 9
        report_balance: true

  - address: "9grKhvEcJDb6xi1Za7GGNgcrWwQaoEAbeSKWPWju5NSPEwcqcn8"
    nickname: "??"
    telegram_destinations:
      - chat_id: "-1002326063811"
        
  - address: "9fuHCh7cvbWxMXdhNpjxAFVGCtP4W3yP6v7vVLPFYB4PR3NpyAL"
    nickname: "??"
    telegram_destinations:
      - chat_id: "-1002326063811"

  - address: "9gPohoQooaGWbZbgTb1JrrqFWiTpM2zBknEwiyDANwmAtAne1Y8"
    nickname: "Ergo Tipper"
    telegram_destinations:
      - chat_id: "-1002326063811"
        
  - address: "9hLEWvxR7uMx3giPyZtobvH2zLjN628gSykjWFAMaG3FjTkShWv"
    nickname: "??"
    telegram_destinations:
      - chat_id: "-1002326063811"

  - address: "9ech2PMseQLoPtibcaT3Bjm52K2AVda3SbHi5vzMAQM7VritCrh"
    nickname: "??"
    telegram_destinations:
      - chat_id: "-1002326063811"

        