version: '3.8'

services:
  ergo-monitor:
    build: .
    container_name: ergo-monitor
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    user: "1000:1000"  # Run as non-root user
    restart: unless-stopped
    environment:
      - TZ=UTC